version: '3.8'
services:
  mysql-e2e:
    image: mysql:8.0
    container_name: mysql_e2e_testing
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: study_space_e2e_db
    ports:
      - "3307:3306" # 3307 from  PC to 3306 of the container
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

      #on terminal:   docker-compose -f docker-compose-e2e.yml up -d