name: SonarCloud Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonar:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      
      #FRONTEND(lcov.info)
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Run Frontend Tests (with Coverage)
        run: |
          cd frontend
          npx ng test --no-watch --code-coverage --browsers=ChromeHeadless

      
      #BACKEND
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Run Backend Tests (with Jacoco)
        run: |
          cd backend
          # 'verify' ejecuta los tests y genera el reporte de Jacoco
          mvn clean verify -DskipTests=false

      
      #SONARCLOUD
    
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    
        with:
          args: >
            -Dsonar.projectKey=codeurjc-students_2025-StudySpace
            -Dsonar.organization=codeurjc-students
            
          
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info
            -Dsonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
            
            
            -Dsonar.exclusions=**/dtos/**,**/dto/**,**/entities/**,**/model/**,**/config/**,**/constants/**,**/*.spec.ts,**/main.ts,**/environment.ts,**/*.module.ts
            -Dsonar.coverage.exclusions=**/dtos/**,**/dto/**,**/entities/**,**/model/**,**/config/**,**/constants/**,**/*.spec.ts,**/main.ts,**/environment.ts,**/*.module.ts